package cz.muni.fi.cpm.template.schema;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import org.openprovenance.prov.model.QualifiedName;

import javax.xml.datatype.XMLGregorianCalendar;
import java.util.List;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class MainActivity {
    @JsonProperty(required = true)
    @JsonPropertyDescription("The identifier of the activity")
    private QualifiedName id;
    @JsonPropertyDescription("The start time of the activity")
    private XMLGregorianCalendar startTime;
    @JsonPropertyDescription("The end time of the activity")
    private XMLGregorianCalendar endTime;
    @JsonPropertyDescription("The identifier of the meta bundle which is referenced by this activity")
    private QualifiedName referencedMetaBundleId;
    @JsonPropertyDescription("The identifier of the activities in domain-specific provenance, that are part of this activity")
    private List<QualifiedName> hasPart;
    @JsonPropertyDescription("The identifiers of the backward connectors that are used by this activity")
    private List<MainActivityUsed> used;
    @JsonPropertyDescription("The identifiers of the forward connectors that are generated by this activity")
    private List<QualifiedName> generated;

    public MainActivity() {
    }

    public MainActivity(QualifiedName id) {
        this.id = id;
    }

    public QualifiedName getId() {
        return id;
    }

    public void setId(QualifiedName id) {
        this.id = id;
    }

    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    public void setStartTime(XMLGregorianCalendar startTime) {
        this.startTime = startTime;
    }

    public XMLGregorianCalendar getEndTime() {
        return endTime;
    }

    public void setEndTime(XMLGregorianCalendar endTime) {
        this.endTime = endTime;
    }

    public QualifiedName getReferencedMetaBundleId() {
        return referencedMetaBundleId;
    }

    public void setReferencedMetaBundleId(QualifiedName referencedMetaBundleId) {
        this.referencedMetaBundleId = referencedMetaBundleId;
    }

    public List<QualifiedName> getHasPart() {
        return hasPart;
    }

    public void setHasPart(List<QualifiedName> hasPart) {
        this.hasPart = hasPart;
    }

    public List<QualifiedName> getGenerated() {
        return generated;
    }

    public void setGenerated(List<QualifiedName> generated) {
        this.generated = generated;
    }

    public List<MainActivityUsed> getUsed() {
        return used;
    }

    public void setUsed(List<MainActivityUsed> used) {
        this.used = used;
    }
}
