name: Java CI with Maven

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 23

      - name: Build with Maven
        run: mvn -B package --file pom.xml